# docs https://github.com/FreshRSS/FreshRSS/tree/edge/Docker
# https://github.com/FreshRSS/FreshRSS
# https://github.com/FreshRSS/Extensions
# configs.env ei ole käytössä.
version: "2.4"

volumes:
  data:
  extensions:

services:

  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
#    ports: #Host:Container
#      - 9080:80
    volumes:
      - /Path/To/freshrss/data:/var/www/FreshRSS/data
      - /Path/To/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Europe/Helsinki
      CRON_MIN: '3,33'